package com.tblf.main;

import com.tblf.classLoading.SingleURLClassLoader;
import com.tblf.instrumentation.ByteCodeInstrumenter;
import com.tblf.parsing.ModelParser;
import com.tblf.runner.JUnitRunner;
import com.tblf.util.ModelUtils;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * Main method of the Application
 */
public class App 
{
    private static final Logger LOGGER = Logger.getAnonymousLogger();
    /**
     * Main method
     * @param args
     * args[0]: xmi model generated by MoDisco
     * args[1]: binaries folder
     * @throws MalformedURLException
     * @throws ClassNotFoundException
     */
    public static void main( String[] args ) throws Exception {
        if (args.length != 2) {
            LOGGER.warning("Incorrect arguments. Expecting [modelUri, binariesUri]");
            return;
        }

        File model = new File(args[0]);
        File binaries = new File(args[1]);

        if (!(model.exists() && binaries.exists())){
            LOGGER.warning("Model or Binaries don't exist");
            return;
        }

        ModelParser modelParser = new ModelParser();
        modelParser.parse(ModelUtils.loadModel(model));

        if (modelParser.getTests().isEmpty() || modelParser.getTargets().isEmpty()) {
            LOGGER.warning("couldnt find test or SUT classes");
            return;
        }

        ByteCodeInstrumenter byteCodeInstrumenter = new ByteCodeInstrumenter(binaries);
        byteCodeInstrumenter.instrument(modelParser.getTargets().keySet(), modelParser.getTests().keySet());

        SingleURLClassLoader.getInstance().addURLs(new URL[]{binaries.toURI().toURL()});
        JUnitRunner jUnitRunner = new JUnitRunner(SingleURLClassLoader.getInstance().getUrlClassLoader());

        jUnitRunner.runTests(modelParser.getTests().keySet());
    }
}
